---
title: "Ars est recta ratio factibilium"
subtitle: "Beasts of Imagination and Right Reason"
date: '2025-12-06'
---

The Manticore is a fictionalized beast that was born in Persian art and literature sometime around its cultural zenith. It at once symbolizes evil, death and hell, but in medieval religious art, came to symbolize the power of Christ over death and hell.

In the 57th question of the 1st of the second part of the Summa Theologica, Thomas Aquinas defends the view of art as a form of right reason. There is a distinction here between right reason for making objects, and right reason for doing good actions. We should first focus on the point that important to both of these activities, is the right use of one's cognitive faculties. The difference lies in the produced object, whether an action or thing.

Considering a product that is produced, the desired outcome of the activity of art, it is not clear what it is exactly, that we care about in the case of art. When it comes to what is produced in the case of art, it is not clear whether the final thing produced is an action, or a material commodity. The common contemporary understanding considers various perspectives. However, it is important to understand two important points here.

@pine21 argues that this is because art's purpose in the middle ages is to represent reality. It is one thing to accurately and factually represent a tree, however, Pinero is talking about more complex reality, especially moral reality.

One example of medieval representations of moral reality include the Persian Manticore.

The manticore as depicted in medieval art is said to represent evil. There are several ways in which some art object may represent more complex realities. One may think that the purpose of a painting is to reflect the experiences one had during a war, or peace time event. Such a painting may express the given facts of the case, for instance an artist could paint the signing of the Magna Carta. If the painting were painted by an artist who was alive to witness the signing of the Magna Carta, then the artist would merely be representing contemporary reality. If the art were not alive at the time, then we could argue that the artist is represeting historical reality. If the artist is relying on trusted sources that are well-known, then this would be different than if the artist were imagining an event which not many direct sources exist. But an artist can represent a projection of reality as well when the reality they want to convey is obscure, not well known, highly contested etc.

> By definition, medieval art implies metaphysical aspirations and normative elements (De Bruyne 1959). Its commitment with reality is undeniable yet the reality which it attempts to represent is so complex and vast that the limits between what is and what is not, between what we believe and what we know, between what we are and what we wish to be, are often blurred. (Cronin 1941)

Here, the artist can represent facts as they believe them to be, or as they wish them to be. It is this latter motivation that Pinero suggests motivated medieval artwork representing the manticore.
