---
title: "The Epistemic Injustice of Authentic Art"
subtitle: "Commentaries on Patricia Collins"
date: '2025-12-07'
---

Wendy @layb18 proposes a criticism of black authenticity and what she calls commodified realness. According to Laybourn, identity is sold to a broader public as black authenticity. This criticism is centered around the effects of what she calls *controlling images* in popular media. Of deep concern here, is that many of the members of the communities depicted by such images consider aspects of these images to be authentic representations and not in themselves harmful. Yet too, this is also a common trope, as old as society.

I present this case as an example of a paradigmatic concept of hermeneutic injustice. It is not clear just what aspects of the member's lives are represented, nor specifically which images are harmful if such images are accepted as representative. An important question here has to do with the relationship between popular narratives that contain these images, and personal identity. One approach argues that we are defined by the stories we accept about ourselves, but this is controversial.

It is not necessarily clear where to find the literature on specifically what is at issue here. Because of this, I think it will be helpful to start with something of an analogy, specifically one from the popular narrative.

In the newest Wicked screen adaptation, there is an underlying story line. The protagonist, the 'wicked' witch finally comes to accept that she will never be accepted by the broader public and as such, will always stand out as a scapegoat of sorts owing to her dark green skin. Therefore she fully leans into her 'wicked' persona.

However, perhaps a detail which could not be included as prominently in Gregory Maguires 1995 novel. The amazing actress, Cynthia Erivo, is an African American with especially prominent African, accentuated owing to the excellent applied makeup and superb acting by Evrivo, features. Through both movies, it is obvious that she isn't green in reality, but African American. We see the story of the witch as a case of othering. As such, especially poignant was the moment when Dorothy, believing the witch can be killed throws a bucket of water on her, an old racist trope about African Americans and bathing.

It is a fortunate accident I suppose, director John M. Chu taking perfect advantage of the fact that the witch in the original dies having had a bucket of water thrown onto her. The witch, fully adopting her role, seemingly for the good of the people of Oz, 'dies', but in the fiction, merely goes into hiding.

Ultimately Elphaba and Prince Fiyero, turned Straw man, strike out to the desert after her sacrificial death accepting that they will forever be scapegoats should they choose to stay in Oz.
